/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary": "#ffffff",
        primary: "#a73a00",
        "surface-container-low": "#f6f3f2",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "on-background": "#1c1b1b",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#802a00",
        "on-secondary-fixed": "#00210c",
        "on-tertiary": "#ffffff",
        error: "#ba1a1a",
        "on-tertiary-fixed": "#1c1c19",
        tertiary: "#5f5e5b",
        "surface-tint": "#a73a00",
        "surface-variant": "#e5e2e1",
        "inverse-on-surface": "#f3f0ef",
        "surface-container": "#f0eded",
        "on-primary-fixed": "#370e00",
        "on-secondary-container": "#0b743b",
        "on-surface": "#1c1b1b",
        background: "#fcf9f8",
        surface: "#fcf9f8",
        "tertiary-fixed-dim": "#c9c6c2",
        "inverse-surface": "#313030",
        "primary-fixed-dim": "#ffb59a",
        secondary: "#006d36",
        "outline-variant": "#e4beb1",
        "primary-fixed": "#ffdbce",
        "inverse-primary": "#ffb59a",
        "surface-container-high": "#eae7e7",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-tertiary-container": "#2b2b28",
        "secondary-fixed-dim": "#7eda95",
        "on-primary-container": "#521800",
        "primary-container": "#ff5c00",
        "on-secondary-fixed-variant": "#005227",
        "surface-dim": "#dcd9d9",
        outline: "#8f7065",
        "secondary-fixed": "#9af7af",
        "surface-container-highest": "#e5e2e1",
        "surface-bright": "#fcf9f8",
        "tertiary-fixed": "#e5e2dd",
        "on-tertiary-fixed-variant": "#474743",
        "on-surface-variant": "#5b4137",
        "tertiary-container": "#94928e",
        "secondary-container": "#9af7af",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "16px",
        "3xl": "24px",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        gutter: "16px",
        base: "8px",
        lg: "40px",
        "margin-desktop": "48px",
        sm: "12px",
        md: "24px",
        xs: "4px",
        xl: "64px",
      },
      fontFamily: {
        "headline-lg": ["Montserrat"],
        "label-md": ["Inter"],
        "body-lg": ["Inter"],
        "label-sm": ["Inter"],
        "headline-lg-mobile": ["Montserrat"],
        "body-md": ["Inter"],
        "display-lg": ["Montserrat"],
        "headline-md": ["Montserrat"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
