export type Category = {
  label: string;
  icon: string;
};

export type Vendor = {
  name: string;
  rating: string;
  time: string;
  delivery: string;
  image: string;
};

export type Meal = {
  name: string;
  rating: string;
  price: string;
  image: string;
  vendor: string;
};

export const categories: Category[] = [
  { label: "Breakfast", icon: "breakfast_dining" },
  { label: "Lunch", icon: "lunch_dining" },
  { label: "Drinks", icon: "local_bar" },
  { label: "Snacks", icon: "cookie" },
  { label: "Local Meals", icon: "restaurant" },
];

// A single sellable item inside a category. Catalog artwork is generated by a
// local route so browsing never depends on an unreliable third-party image API.
export type CatalogItem = {
  id: string;
  name: string;
  vendor: string;
  price: number;
  image: string;
  tag?: string;
};

const photo = (keywords: string, lock: number) =>
  `/api/catalog-image?keywords=${encodeURIComponent(keywords)}&lock=${lock}`;

// Products grouped by the category label they live under. Drinks is the most
// stocked shelf — every kind of thing you'd grab at a kibanda is here.
export const catalog: Record<string, CatalogItem[]> = {
  Breakfast: [
    { id: "breakfast-chai-maziwa", name: "Chai ya Maziwa", vendor: "Mama Njeri's Kitchen", price: 30, image: photo("kenyan,tea", 101) },
    { id: "breakfast-chai-mandazi", name: "Chai and 2 Mandazi", vendor: "Mama Njeri's Kitchen", price: 60, image: photo("tea,mandazi", 102), tag: "Mwananchi Favourite" },
    { id: "breakfast-chai-chapati", name: "Chai and Chapati", vendor: "Mama Njeri's Kitchen", price: 60, image: photo("tea,chapati", 103) },
    { id: "breakfast-uji-wimbi", name: "Uji wa Wimbi", vendor: "Wakulima Fresh", price: 40, image: photo("millet,porridge", 104) },
    { id: "breakfast-uji-power", name: "Uji Power", vendor: "Wakulima Fresh", price: 60, image: photo("porridge,cup", 105) },
    { id: "breakfast-bread-chai", name: "Bread and Chai", vendor: "Mama Njeri's Kitchen", price: 50, image: photo("bread,tea", 106) },
    { id: "breakfast-viazi-vitamu", name: "Viazi Vitamu and Chai", vendor: "Wakulima Fresh", price: 70, image: photo("sweetpotato,tea", 107) },
    { id: "breakfast-nduma-chai", name: "Nduma and Chai", vendor: "Wakulima Fresh", price: 80, image: photo("taro,tea", 108) },
    { id: "breakfast-eggs-chapati", name: "Two Eggs and Chapati", vendor: "Mama Njeri's Kitchen", price: 120, image: photo("eggs,chapati", 109), tag: "Popular" },
    { id: "breakfast-mahamri-mbaazi", name: "Mahamri and Mbaazi", vendor: "Swahili Dishes", price: 120, image: photo("mahamri,peas", 110), tag: "Coastal" },
  ],
  Lunch: [
    { id: "beef-pilau", name: "Beef Pilau", vendor: "The Pilau Master", price: 250, image: photo("pilau,rice", 121), tag: "Chef's pick" },
    { id: "chicken-biryani", name: "Chicken Biryani", vendor: "The Pilau Master", price: 380, image: photo("biryani,rice", 122) },
    { id: "ugali-stew", name: "Ugali & Beef Stew", vendor: "Mama Njeri's Kitchen", price: 280, image: photo("beef,stew", 123) },
    { id: "rice-beans", name: "Rice & Beans", vendor: "Wakulima Fresh", price: 180, image: photo("rice,beans", 124) },
    { id: "chapati-ndengu", name: "Chapati & Ndengu", vendor: "Mama Njeri's Kitchen", price: 150, image: photo("chapati,curry", 125) },
    { id: "fish-ugali", name: "Fish & Ugali", vendor: "Choma Zone", price: 350, image: photo("fish,fried", 126) },
    { id: "beef-rice", name: "Beef Stew & Rice", vendor: "The Pilau Master", price: 260, image: photo("rice,beef", 127) },
  ],
  Drinks: [
    { id: "drink-chai-maziwa", name: "Chai ya Maziwa", vendor: "Mama Njeri's Kitchen", price: 30, image: photo("kenyan,milk,tea", 141), tag: "Mwananchi Favourite" },
    { id: "drink-chai-tangawizi", name: "Chai ya Tangawizi", vendor: "Mama Njeri's Kitchen", price: 40, image: photo("ginger,tea", 142) },
    { id: "drink-chai-kavu", name: "Chai Kavu", vendor: "Mama Njeri's Kitchen", price: 20, image: photo("black,tea", 143) },
    { id: "drink-kenyan-coffee", name: "Kenyan Coffee", vendor: "Kibanda Express", price: 50, image: photo("kenyan,coffee", 144) },
    { id: "drink-mala-250ml", name: "Mala 250ml", vendor: "Wakulima Fresh", price: 70, image: photo("fermented,milk", 145) },
    { id: "drink-soda-300ml", name: "Soda 300ml", vendor: "Kibanda Express", price: 50, image: photo("soda,bottle", 146) },
    { id: "drink-soda-500ml", name: "Soda 500ml", vendor: "Kibanda Express", price: 70, image: photo("softdrink,bottle", 147) },
    { id: "drink-water-500ml", name: "Mineral Water 500ml", vendor: "Kibanda Express", price: 40, image: photo("water,bottle", 148) },
    { id: "drink-passion-juice", name: "Fresh Passion Juice", vendor: "Wakulima Fresh", price: 80, image: photo("passionfruit,juice", 149), tag: "Fresh" },
    { id: "drink-mango-juice", name: "Fresh Mango Juice", vendor: "Wakulima Fresh", price: 80, image: photo("mango,juice", 150) },
    { id: "drink-sugarcane-juice", name: "Sugarcane Juice", vendor: "Wakulima Fresh", price: 60, image: photo("sugarcane,juice", 151) },
    { id: "drink-ukwaju-juice", name: "Ukwaju Juice", vendor: "Swahili Dishes", price: 50, image: photo("tamarind,juice", 152), tag: "Coastal" },
    { id: "drink-dawa", name: "Dawa: Lemon, Ginger and Honey", vendor: "Mama Njeri's Kitchen", price: 70, image: photo("lemon,ginger,honey", 153) },
    { id: "drink-stoney-500ml", name: "Stoney Tangawizi 500ml", vendor: "Kibanda Express", price: 70, image: photo("ginger,soda", 154) },
  ],
  Snacks: [
    { id: "snack-mandazi", name: "Mandazi", vendor: "Mama Njeri's Kitchen", price: 15, image: photo("mandazi,donut", 161) },
    { id: "snack-mahamri", name: "Mahamri", vendor: "Swahili Dishes", price: 20, image: photo("mahamri,pastry", 162), tag: "Coastal" },
    { id: "snack-beef-samosa", name: "Beef Samosa", vendor: "Swahili Dishes", price: 40, image: photo("beef,samosa", 163), tag: "Bestseller" },
    { id: "snack-vegetable-samosa", name: "Vegetable Samosa", vendor: "Swahili Dishes", price: 30, image: photo("vegetable,samosa", 164) },
    { id: "snack-smokie", name: "Smokie", vendor: "Kibanda Express", price: 40, image: photo("smoked,sausage", 165) },
    { id: "snack-smokie-pasua", name: "Smokie Pasua with Kachumbari", vendor: "Kibanda Express", price: 50, image: photo("sausage,tomato", 166), tag: "Popular" },
    { id: "snack-boiled-egg", name: "Boiled Egg", vendor: "Kibanda Express", price: 30, image: photo("boiled,egg", 167) },
    { id: "snack-egg-pasua", name: "Egg Pasua with Kachumbari", vendor: "Kibanda Express", price: 40, image: photo("egg,tomato", 168) },
    { id: "snack-sausage", name: "Sausage", vendor: "Choma Zone", price: 50, image: photo("sausage,grilled", 169) },
    { id: "snack-viazi-karai", name: "Viazi Karai (4 pieces)", vendor: "Swahili Dishes", price: 80, image: photo("potato,fritters", 170), tag: "Coastal" },
    { id: "snack-bhajia", name: "Bhajia Portion", vendor: "Swahili Dishes", price: 100, image: photo("potato,bhajia", 171) },
    { id: "snack-roasted-maize", name: "Roasted Maize", vendor: "Choma Zone", price: 50, image: photo("corn,grilled", 172) },
    { id: "snack-groundnuts", name: "Roasted Groundnuts", vendor: "Wakulima Fresh", price: 30, image: photo("peanuts,roasted", 173) },
    { id: "snack-mutura", name: "Mutura Portion", vendor: "Choma Zone", price: 100, image: photo("mutura,sausage", 174) },
  ],
  "Local Meals": [
    { id: "meal-ugali-sukuma", name: "Ugali and Sukuma Wiki", vendor: "Mama Njeri's Kitchen", price: 100, image: photo("ugali,greens", 181), tag: "Mwananchi Favourite" },
    { id: "meal-ugali-cabbage", name: "Ugali and Cabbage", vendor: "Mama Njeri's Kitchen", price: 100, image: photo("ugali,cabbage", 182) },
    { id: "meal-ugali-managu", name: "Ugali and Managu", vendor: "Wakulima Fresh", price: 120, image: photo("ugali,african,greens", 183) },
    { id: "meal-githeri", name: "Githeri", vendor: "Wakulima Fresh", price: 100, image: photo("maize,beans", 184), tag: "Mwananchi Favourite" },
    { id: "meal-rice-beans", name: "Rice and Beans", vendor: "Wakulima Fresh", price: 120, image: photo("rice,beans", 185) },
    { id: "meal-chapati-beans", name: "Chapati and Beans", vendor: "Mama Njeri's Kitchen", price: 100, image: photo("chapati,beans", 186) },
    { id: "meal-chapati-ndengu", name: "Chapati and Ndengu", vendor: "Mama Njeri's Kitchen", price: 100, image: photo("chapati,lentils", 187) },
    { id: "meal-ugali-omena", name: "Ugali and Omena", vendor: "Mama Njeri's Kitchen", price: 150, image: photo("ugali,smallfish", 188) },
    { id: "meal-ugali-matumbo", name: "Ugali and Matumbo", vendor: "Mama Njeri's Kitchen", price: 180, image: photo("ugali,tripe,stew", 189), tag: "Popular" },
    { id: "meal-ugali-beef-stew", name: "Ugali and Beef Stew", vendor: "Mama Njeri's Kitchen", price: 220, image: photo("ugali,beef,stew", 190) },
    { id: "meal-rice-beef-stew", name: "Rice and Beef Stew", vendor: "Mama Njeri's Kitchen", price: 220, image: photo("rice,beef,stew", 191) },
    { id: "meal-matoke-stew", name: "Matoke Stew", vendor: "Mama Njeri's Kitchen", price: 180, image: photo("plantain,stew", 192) },
    { id: "meal-matoke-beef", name: "Matoke and Beef", vendor: "Mama Njeri's Kitchen", price: 220, image: photo("plantain,beef", 193) },
    { id: "meal-mukimo-beef", name: "Mukimo and Beef Stew", vendor: "Mama Njeri's Kitchen", price: 250, image: photo("mashed,potato,beef", 194) },
    { id: "meal-beef-pilau", name: "Beef Pilau", vendor: "The Pilau Master", price: 200, image: photo("pilau,rice,beef", 195), tag: "Popular" },
    { id: "meal-fish-ugali", name: "Fish and Ugali", vendor: "Choma Zone", price: 280, image: photo("fish,ugali", 196) },
    { id: "meal-quarter-chicken", name: "Quarter Chicken, Ugali and Sukuma", vendor: "Choma Zone", price: 280, image: photo("chicken,ugali,greens", 197) },
    { id: "meal-nyama-choma", name: "Quarter Kilo Nyama Choma and Ugali", vendor: "Choma Zone", price: 300, image: photo("grilled,beef,ugali", 198) },
  ],
};

export const vendors: Vendor[] = [
  {
    name: "Mama Njeri's Kitchen",
    rating: "4.8",
    time: "20-30 min",
    delivery: "Free",
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuAWe_lKF8YJkcFVa35gcSpfvaUHLvqgtFpWNb9sI85ZLWMOfW0sHdQwmaEwEHQxp9MtEPjo430R6wecREvPitC02iA8-ZRCrlbjTTDUvhf4_Eh2r92G5-XhUsZ2ikpzImgM_ZEWGM4jFOtoSWDrWwHPo_nBT0-yAKp02aPxYxUNjKbP0p2lQEweQ0_9XIRgMWCTw4O2j5wZa1hbEg0xMxvvmgYoy3ES3de7H98wKghFELCB6u0FYUe6rZ8MiwI2qJg8O2t39J_0bEDT",
  },
  {
    name: "The Pilau Master",
    rating: "4.5",
    time: "15-25 min",
    delivery: "KSh 50",
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuA9gFIfCo-UDoBaa1eoaOXlV980jvhVowdIedCCq4irJztRcvITswtxpOozCfycsVgAO4h0lKbFh59FXNHodYqDVXcruGUcxvV6U_U2Ds80Ey_Ta_wmbjLuSPNQTn8_E5gRaluKTafCmeSDamuOTgArU_xP-b_f1plh0AepleHbquGetqWLsuiCeqLb-IS2cvGN_KjoakwaWI1CuQpTe4V2gt0dufLbd4WKyyVjvXqGBZw9Y55pJM2DsbSAFxzThNewTaIIPaG7D-sN",
  },
];

export type CartLine = {
  id: string;
  name: string;
  vendor: string;
  price: number;
  qty: number;
  image: string;
  note?: string;
};

export type OrderStatus = "preparing" | "on-the-way" | "delivered" | "cancelled";

export type Order = {
  id: string;
  vendor: string;
  placedAt: string;
  status: OrderStatus;
  total: number;
  items: { name: string; qty: number }[];
  eta?: string;
  image: string;
};

export type Profile = {
  name: string;
  phone: string;
  email: string;
  avatar: string;
  joined: string;
  stats: { orders: number; saved: number; points: number };
};

export const cartLines: CartLine[] = [
  {
    id: "nyama-choma",
    name: "Beef Nyama Choma",
    vendor: "Mama Njeri's Kitchen",
    price: 450,
    qty: 1,
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuAuGqhYYUakZb4_DNrPkGWbiGPJHq_H3AuhniEjV6IcJ5EUyK2-CgFoW-Leny7VhCC4iXfDVuuvE5Tm8rycizzImfHjFC5dXk0DevC_HoLU80iEyW_aotmHKzWE2tc63u7Az6E9pfyRKKYAbUd23i_I5hQhgwj_ETpgUkG8Vc_RT2OPmfgMJG3OIDq_K9SU1xX7xm9rfDbJjo0VUpGkHXEA3sNnXnQ0h3MkeeT4TmQvex6ZddTP1sKIlhgJpCJb4io2x6OubATmQYr_",
    note: "Extra kachumbari on the side",
  },
  {
    id: "biryani",
    name: "Chicken Biryani",
    vendor: "The Pilau Master",
    price: 380,
    qty: 2,
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuAjfDxuBFuiurPfYAf6AH4JZhhp-Pa7igcXBWy1vT9iNnwHX6-EpZbJKZeWYqqs5hU06RWIFP-bUmAvgEA-54uivJvv9xrh-bEr1geLf2wXwgEP9OcQX7pDA0FG0C49mqbne4wirjwt4cEJSs5B22z8mqqKLYXZes720_2uBNOzgCUFjA1u6OXx1WFLPKe0Pfgvb66sHDy3lJKfsxKbDQ-L5dbn0v5AYLcalQI5_9v2047sSofgVv-W9aaC0u_z3bcwYzoM-dN2nt5l",
  },
];

export const orders: Order[] = [
  {
    id: "KE-20418",
    vendor: "Mama Njeri's Kitchen",
    placedAt: "Today, 1:24 PM",
    status: "on-the-way",
    total: 830,
    eta: "12 min away",
    items: [
      { name: "Beef Nyama Choma", qty: 1 },
      { name: "Ugali & Sukuma", qty: 2 },
    ],
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuAuGqhYYUakZb4_DNrPkGWbiGPJHq_H3AuhniEjV6IcJ5EUyK2-CgFoW-Leny7VhCC4iXfDVuuvE5Tm8rycizzImfHjFC5dXk0DevC_HoLU80iEyW_aotmHKzWE2tc63u7Az6E9pfyRKKYAbUd23i_I5hQhgwj_ETpgUkG8Vc_RT2OPmfgMJG3OIDq_K9SU1xX7xm9rfDbJjo0VUpGkHXEA3sNnXnQ0h3MkeeT4TmQvex6ZddTP1sKIlhgJpCJb4io2x6OubATmQYr_",
  },
  {
    id: "KE-20355",
    vendor: "The Pilau Master",
    placedAt: "Yesterday, 7:48 PM",
    status: "delivered",
    total: 760,
    items: [{ name: "Chicken Biryani", qty: 2 }],
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuAjfDxuBFuiurPfYAf6AH4JZhhp-Pa7igcXBWy1vT9iNnwHX6-EpZbJKZeWYqqs5hU06RWIFP-bUmAvgEA-54uivJvv9xrh-bEr1geLf2wXwgEP9OcQX7pDA0FG0C49mqbne4wirjwt4cEJSs5B22z8mqqKLYXZes720_2uBNOzgCUFjA1u6OXx1WFLPKe0Pfgvb66sHDy3lJKfsxKbDQ-L5dbn0v5AYLcalQI5_9v2047sSofgVv-W9aaC0u_z3bcwYzoM-dN2nt5l",
  },
  {
    id: "KE-20189",
    vendor: "Mama Njeri's Kitchen",
    placedAt: "Mon, 17 Jun",
    status: "delivered",
    total: 150,
    items: [{ name: "Kibanda Breakfast", qty: 1 }],
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDqMQ1p1Jr0kWePDInsL0RipSWc42Z-XTUulETonJQFk7aRYQUEzyhyoCGdFc-SfGB5ux39XG215CsOjzWlKSksHv2Th9_cEWktTt7FAsr1UNK9tOqVQddSc5ap74wNQClM8yjX8Lup0Qn9RWCxs7D1mc23KwgMY1PKmFaRx-I3OdJQzOkgZR7SNQ9fVITFRmHnUD9GzPplWPa58V0nRhJ3JoRdJIs4G2jWBW7tIKPsiVO3tG3qdAib2R51VBuvZAQlTzrxJG8UZy_8",
  },
];

export const profile: Profile = {
  name: "Brian Otieno",
  phone: "+254 712 345 678",
  email: "brian.otieno@gmail.com",
  avatar:
    "https://lh3.googleusercontent.com/aida-public/AB6AXuAWe_lKF8YJkcFVa35gcSpfvaUHLvqgtFpWNb9sI85ZLWMOfW0sHdQwmaEwEHQxp9MtEPjo430R6wecREvPitC02iA8-ZRCrlbjTTDUvhf4_Eh2r92G5-XhUsZ2ikpzImgM_ZEWGM4jFOtoSWDrWwHPo_nBT0-yAKp02aPxYxUNjKbP0p2lQEweQ0_9XIRgMWCTw4O2j5wZa1hbEg0xMxvvmgYoy3ES3de7H98wKghFELCB6u0FYUe6rZ8MiwI2qJg8O2t39J_0bEDT",
  joined: "Member since 2024",
  stats: { orders: 42, saved: 8, points: 1280 },
};

export const meals: Meal[] = [
  {
    name: "Beef Nyama Choma",
    rating: "4.9 (120+)",
    price: "KSh 450",
    vendor: "Mama Njeri's Kitchen",
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuAuGqhYYUakZb4_DNrPkGWbiGPJHq_H3AuhniEjV6IcJ5EUyK2-CgFoW-Leny7VhCC4iXfDVuuvE5Tm8rycizzImfHjFC5dXk0DevC_HoLU80iEyW_aotmHKzWE2tc63u7Az6E9pfyRKKYAbUd23i_I5hQhgwj_ETpgUkG8Vc_RT2OPmfgMJG3OIDq_K9SU1xX7xm9rfDbJjo0VUpGkHXEA3sNnXnQ0h3MkeeT4TmQvex6ZddTP1sKIlhgJpCJb4io2x6OubATmQYr_",
  },
  {
    name: "Chicken Biryani",
    rating: "4.7 (85+)",
    price: "KSh 380",
    vendor: "The Pilau Master",
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuAjfDxuBFuiurPfYAf6AH4JZhhp-Pa7igcXBWy1vT9iNnwHX6-EpZbJKZeWYqqs5hU06RWIFP-bUmAvgEA-54uivJvv9xrh-bEr1geLf2wXwgEP9OcQX7pDA0FG0C49mqbne4wirjwt4cEJSs5B22z8mqqKLYXZes720_2uBNOzgCUFjA1u6OXx1WFLPKe0Pfgvb66sHDy3lJKfsxKbDQ-L5dbn0v5AYLcalQI5_9v2047sSofgVv-W9aaC0u_z3bcwYzoM-dN2nt5l",
  },
  {
    name: "Fruit Platter Extra",
    rating: "4.5 (50+)",
    price: "KSh 250",
    vendor: "Mama Njeri's Kitchen",
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDLfwTahaCSYLakSapRtim_s63LPCJFz4o7ovT14zL16resrqJ6xsHHFur_SM0QzIZZZRNjP7dPZ8vk2yWB8D2hVHphjZYMDm5gzKq60kQe3umSVsbNuAR7a1RndaxbO43XVg_O0TtiAyZDFz0zNvQjrqWddBnCIhgODI4ZcdNXheVrtRwpsOyHf9oWLVf_wENfZcndOatZHqCWG6fCgYE0IfM9gqbLTRXrk9mwhG7PMJlOtMhH1MtdLFdO75s2b17AUZHCsHMoPChJ",
  },
  {
    name: "Kibanda Breakfast",
    rating: "4.8 (200+)",
    price: "KSh 150",
    vendor: "Mama Njeri's Kitchen",
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDqMQ1p1Jr0kWePDInsL0RipSWc42Z-XTUulETonJQFk7aRYQUEzyhyoCGdFc-SfGB5ux39XG215CsOjzWlKSksHv2Th9_cEWktTt7FAsr1UNK9tOqVQddSc5ap74wNQClM8yjX8Lup0Qn9RWCxs7D1mc23KwgMY1PKmFaRx-I3OdJQzOkgZR7SNQ9fVITFRmHnUD9GzPplWPa58V0nRhJ3JoRdJIs4G2jWBW7tIKPsiVO3tG3qdAib2R51VBuvZAQlTzrxJG8UZy_8",
  },
];
